blank_issues_enabled: true
  - name: Discussions
    url: https://github.com/DoubleML/doubleml-for-py/discussions/new
    about: Ask questions about DoubleML or start related dicussions
  - name: Blank Issue
    url: https://github.com/DoubleML/doubleml-for-py/issues/new
    about: Please note that often Dicussions is the better choice
