name: Feature Request
description: Suggest an enhancement or extension for the DoubleML package
title: "[Feature Request]: "
labels: ["new feature", "enhancement"]

body:
- type: textarea
  attributes:
    label: Describe the feature you want to propose or implement
  validations:
    required: true
- type: textarea
  attributes:
    label: Propose a possible solution or implementation
- type: textarea
  attributes:
    label: Did you consider alternatives to the proposed solution. If yes, please describe
- type: textarea
  attributes:
    label: Comments, context or references
