# Workflow based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: CI deploy documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  release:
    types:
      - published


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Check out the repo containing the R docu
      uses: actions/checkout@master
      with:
        repository: DoubleML/doubleml-for-r

    - name: Install SSH Client for deploying the docu to github pages
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Install graphviz
      run: sudo apt-get install graphviz

    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install .

    - name: Install R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: 'release'
    - name: Install R kernel for Jupyter
      run: |
        install.packages('remotes')
        install.packages('IRkernel')
        IRkernel::installspec()
      shell: Rscript {0}

    - name: Query dependencies for r package DoubleML
      run: |
        install.packages('remotes')
        saveRDS(remotes::dev_package_deps(pkgdir = "doubleml-for-r", dependencies = TRUE), ".github/depends.Rds", version = 2)
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}
    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
    - name: Install system dependencies package
      run: |
        while read -r cmd
        do
          eval sudo $cmd
        done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04", path = "doubleml-for-r"))')
    - name: Install dependencies
      run: |
        remotes::install_deps(pkgdir = "doubleml-for-r", dependencies = TRUE)
      shell: Rscript {0}
    - name: Install package
      run: R CMD INSTALL doubleml-for-r

    - name: Build docu with sphinx
      run: |
        make -C doc html # build docu

    - name: Deploy to dev
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        REPOSITORY_NAME: DoubleML/doubleml.github.io
        BRANCH: master
        FOLDER: doc/_build/html
        TARGET_FOLDER: dev
        GIT_CONFIG_NAME: DoubleML Deploy Bot
        GIT_CONFIG_EMAIL: DoubleML@users.noreply.github.com
        CLEAN: true
        SSH: true

    - name: Get tag
      run: echo RELEASE_VERSION=${GITHUB_REF:10} >> $GITHUB_ENV

    - name: Deploy to version
      if: ${{ github.event_name == 'release'}}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        REPOSITORY_NAME: DoubleML/doubleml.github.io
        BRANCH: master
        FOLDER: doc/_build/html
        TARGET_FOLDER: ${{env.RELEASE_VERSION}}
        GIT_CONFIG_NAME: DoubleML Deploy Bot
        GIT_CONFIG_EMAIL: DoubleML@users.noreply.github.com
        CLEAN: true
        SSH: true

    - name: Deploy to stable
      if: ${{ github.event_name == 'release' }}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        REPOSITORY_NAME: DoubleML/doubleml.github.io
        BRANCH: master
        FOLDER: doc/_build/html
        TARGET_FOLDER: stable
        GIT_CONFIG_NAME: DoubleML Deploy Bot
        GIT_CONFIG_EMAIL: DoubleML@users.noreply.github.com
        CLEAN: true
        SSH: true
