# Workflow based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: CI unit tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install .
    - name: Build docu with sphinx
      run: |
        make -C doc html # build docu
